### ISSUE TITLE
javax.persistence.PersistenceException

### ISSUE THREAD

**Issue by johannesgiani** [agoncal/agoncal-application-petstore-ee7#10]
When creating a new account the following message is printed in the front end on submitting firstname, lastname, country, ...
    	javax.persistence.PersistenceException: org.hibernate.PersistentObjectException: detached entity passed to persist: org.agoncal.application.petstore.model.Country

**Comment by agoncal** [comment]
Fixed with https://github.com/agoncal/agoncal-application-petstore-ee7/commit/143ee883a890c30d24b52ad451d4dff1e5adfb0f
