### ISSUE TITLE
Petstore not loaded under Tomcat 9

### ISSUE THREAD

**Issue by balderman1** [agoncal/agoncal-application-petstore-ee7#14]
I have built the app using maven and deployed the war under Tomcat 9.
I point my browser to http://localhost:8080/applicationPetstore and get

```
HTTP Status 404 – Not Found
Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.10
```
The URL in the browser changed to http://localhost:8080/applicationPetstore/shopping/main.xhtml

**Comment by saravanan-kandaswamy** [comment]
Deployment in Tomcat will not work since it doesn't have EJB Container. You should try in Wildfly/JBoss EAP/Glass fish/Payara server where the Application server is compatible with JEE 7.
