### ISSUE TITLE
Error Running Tests

### ISSUE THREAD

**Issue by tomdeering-ensoft** [agoncal/agoncal-application-petstore-ee7#4]
Running the tests with "mvn -Pglassfish4-embedded-all clean install" crashes and burns. An initial error is encountered:

```
Aug 16, 2013 9:07:31 AM org.glassfish.api.ActionReport failure
SEVERE: Exception while invoking class org.glassfish.persistence.jpa.JPADeployer prepare method
java.lang.RuntimeException: Invalid resource : jdbc/petstore__pm
```

Followed by this error on 5 of the tests:

```
java.lang.IllegalArgumentException: ArquillianServletRunner not found. Could not determine ContextRoot from ProtocolMetadata, please contact DeployableContainer developer.
```

Why are the tests encountering these errors?

**Comment by peturingi** [comment]
I get the same error.

**Comment by agoncal** [comment]
I got rid of GlassFish. Use Wildfly 8 or 9 (in a remote mode) and just type :  mvn clean test -Parquillian-wildfly-remote
